package Ejercicios789;

import java.io.IOException;

public class ExcepcionThrows {

    /**
     * Crea una función DividePorCero.
     * Esta, debe generar una excepción ("throws")
     * a su llamante del tipo ArithmeticException que será capturada por su llamante (desde "main",
     * por ejemplo).
     * Si se dispara la excepción,
     * mostraremos el mensaje "Esto no puede hacerse".
     * Finalmente, mostraremos en cualquier caso: "Demo de código".
     */
    public static void main(String[] args) {
        try {
            DividePorCero(4, 0);
        } catch (Exception e) {
            System.out.println("Demo de codigo");
        }
    }
    public static int DividePorCero(int A, int B) throws ArithmeticException, IOException {
        int resultado = 0;
        try {
            resultado = A / B;

        } catch (ArithmeticException e) {
            System.out.println("Esto no puede hacerse");
            throw new IOException();
        }

        return resultado;

    }


}
